config/routes.rb
Stock::Application.routes.draw do
  devise_for :users

  resources :products

  root :to => 'main#index'

end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  validates :name, :price, :status, :presence => true
  validates :email, :presence => true, :if => "phone.blank?"
  validates :phone, :presence => true, :if => "email.blank?"
  validates :price, :numericality => { :only_integer => true, :greater_than => 0}

  attr_accessible :name, :status, :price, :description, :phone, :email, :product_images, :product_images_attributes
  STATUSES = {:used =>"БУ", :new =>"Новый"}

  has_many :product_images
  accepts_nested_attributes_for :product_images, :reject_if => lambda { |a| a[:image].blank? }
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :image

  #attr_accessor :image_file_name
  has_attached_file :image,
                    :path => ":rails_root/public:url",
                    :url => "/system/products/:product_id/:class/:id/:style/:filename",
                    :default_url => "/public/missing/:category_name.png",
                    :styles => { :medium => "200x200>", :thumb => "100x100#" }
  validates_attachment_size :image, :less_than => 5.megabytes

  belongs_to :product, :dependent =>:destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    page = params[:page] || 1
    per_page||=2
    @products = Product.paginate(:page => page, :per_page => per_page)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :except => ["index", "show"]

  def index

  end

  def new
    @product = Product.new
    3.times{@product.product_images.build}
    #@product.product_images.build
  end

  def create
    @product = Product.new(params[:product])
    if @product.valid?
      @product.save!
      redirect_to :action => "show", :id => @product.id
    else
      render :action => "new"
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :alert
        "alert-block"
      when :error
        "alert-error"
      when :notice
        "alert-info"
      when :success
        "alert-success"
      else
        type.to_s
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset=>'utf-8'}
    %title= "Stock"
    = stylesheet_link_tag  "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      #logo
        %a{:href => "/"} Футбольный базар
      #add_product_container
        =link_to "Создать объявление", new_product_path, :class => "btn btn-warning"
      #menu
        - if user_signed_in?
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Мои страницы
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Выйти", destroy_user_session_path, :method => "DELETE"
        - else
          %ul.nav.nav-pills
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Войти
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "По e-mail", new_user_session_path
                -#%li.divider
                -#%li
                -#  %a{:href=>"#"}= "Вконтакте"
                -#%li
                -#  %a{:href=>"#"}= "Facebook"
                -#%li
                -#  %a{:href=>"#"}= "Google"
    #content
      .content_inner
        - flash.each do |type, message|
          .alert.fade.in{ "data-alert" => "alert", :class => twitterized_type(type) }
            %a.close{href: "#", data: {dismiss: 'alert'}} &times;
            %h4= message
        #columns
          #left
            .left_inner
              = yield
          #right
            -#.right_inner
            -#  .block.stuck.about
            -#    %h4 Размещайте вакансии
            -#    %p Мы предлагаем интересную услугу на рынке вакансий: ваше объявление увидят лучшие специалисты из индустрии информационных технологий. Все размещения премиальные, поэтому у нас только лучшие вакансии от лучших компаний.
            -#    %button.button.buy_code{:onclick => "document.location.href='/buy_code'"}
            -#      %span купить
            -#  .social.block
            -#    %h4 Мы в социальных сетях
            -#    %a.twitter{:href => "https://twitter.com/#!/hantim_ru"} Twitter
            -#    %a.facebook{:href => "http://www.facebook.com/pages/HANTIMRU/291424447548996"} Facebook
            -#  .facebook.block
            -#    %h4 Facebook
            -#    %iframe{:allowTransparency => "true", :frameborder => "0", :scrolling => "no", :src => "//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FHANTIMRU%2F291424447548996&width=196&colorscheme=light&show_faces=true&border_color=%23fff&stream=false&header=false&height=330&appId=242988179070978", :style => "border:none; overflow:hidden; width:196px; height:330px;"}
            -#  .vkontakte.block
            -#    %h4 ВКонтакте
            -#    #vk_groups
            -#      :javascript
            -#        //
            -#          VK.Widgets.Group("vk_groups", {mode: 0, width: "200", height: "330"}, 36860008);
            -#        //
            -#  .block.stuck.webmoney
            -#    %a{:href => "http://webmoney.ru/"}
            -#      %img{:alt => "Webmoney", :src => "/images/webmoney.png?1342159675"}/
    #footer
      %a{:href => "#"} О проекте
      %a.copy{:href => "#"}
        %span
          © 2012
        %em

app/views/main/index.html.haml
.items
  .list
    = render :partial =>"products/product_item", :collection => @products
= will_paginate @products, :renderer => BootstrapPagination::Rails

app/views/products/_product_item.html.haml
%a.item{:href => "#{product_path(product_item.id)}"}
  .job_icon
    = image_tag product_item.product_images.first.image.url(:medium)
    -#%img{:alt => "", :src => "http://shop.football.kharkov.ua/files/products/206_0.95x95.jpg?b72265546ac07e15453883ae228e01fb"}/
  .meta
    %span.city Харьков
    .published= "#{time_ago_in_words(product_item.created_at)} назад"
  .price= "#{product_item.price} грн"
  .position
    .title= "#{product_item.name}"
    %span.badge= Product::STATUSES[product_item.status.to_sym]

app/views/products/index.html.haml
index

app/views/products/new.html.haml
%h1 Новое объявление
= simple_form_for @product, :html =>{:class =>"form-horizontal"} do |f|
  %legend= "Информация о товаре"
  = f.input :name, :input_html => {:class => "span3"}, :placeholder =>"футбольный мяч", :label => "Название"
  - options = []
  - Product::STATUSES.each{|key, value| options << [value, key]}
  = f.input :status, :label => "Состояние", :input_html => {:class => "input-small"}, :include_blank => false, :collection => options
  = f.input :price, :wrapper => :append, :label => "Цена" do
    = f.input_field :price, :class => "input-small", :placeholder =>"100"
    = content_tag :span, "грн", :class => "add-on"
  = f.input :description, :input_html => {:class => "span3", :rows =>"4"}, :label => "Описание"
  = f.simple_fields_for :product_images do |p|
    = p.input :image, :as => "file"
  %legend= "Информация о продавце"
  = f.input :phone, :input_html => {:class => "span3"}, :label => "Телефон"
  .control-group
    %span= "Или"
  = f.input :email, :input_html => {:class => "span3"}, :label => "E-mail"
  .form-actions
    = f.button :submit, :value=>"Сохранить", :name => "create", :class =>"btn btn-success"

app/views/products/show.html.haml
%h1= @product.name
%span.badge= @product.status
%div{:style =>"clear: both;margin-bottom: 5px;"}

-#TODO Replace with photo
- if @product.product_images.count == 0
  %div{:style => "width: 200px;height: 160px; border:1px dashed grey; float: left;margin: 0 10px 5px 0; padding-top: 40px;text-align: center;"}= "Фото отсутствует"
- else
  =image_tag @product.product_images.first.image.url(:medium), :style => "float: left;margin: 0 10px 5px 0;"
%span.price.big_price= "#{@product.price} грн"

%p
  = @product.description
%div.conacts
  %p
    = "Контакты"

%div{:style =>"clear: both;margin-bottom: 5px;"}

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Войти", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Регистрация", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Забыли пароль?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Не получили инструкции по активации учетной записи?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Не получили инструкции по разблокированию учетной записи?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Войти через #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/